image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - sonarscanner

variables:
  SOLUTION: "PassIn.sln"
  SONAR_PROJECT_KEY: "passin"
  SONAR_USER: "admin"
  SONAR_PASS: "admin1"
  SONAR_HOST_URL: "http://localhost:9000" # URL do servidor SonarQube
  SONAR_TOKEN: "8499d72db78c461d172edde4c1b2eafc4d9348a3" # Token de autenticação do SonarQube
  TEST_PATH: "tests"
  UNIT_TEST: "UnitTests"
  REPORTS_PATH: "/builds/StephHoel/PassIn-NLW-UNITE/"

build:
  stage: build
  script:
    - dotnet restore $SOLUTION
    - dotnet build $SOLUTION --no-incremental 

test:
  stage: test
  script:
    - cd $TEST_PATH/$UNIT_TEST
    - dotnet build --no-incremental
    - dotnet test

sonarscanner:
  stage: sonarscanner
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install --global coverlet.console
    - dotnet tool install --global dotnet-sonarscanner --version 4.10.0
    - dotnet sonarscanner begin -key:"$SONAR_PROJECT_KEY" -d:sonar.login="$SONAR_USER" -d:sonar.password="$SONAR_PASS" -d:sonar.token="$SONAR_TOKEN" -d:sonar.cs.opencover.reportsPaths="$REPORTS_PATH\coverage.xml" -d:sonar.analysis.mode="publish"
    - dotnet build --no-incremental 
    - coverlet $TEST_PATH/$UNIT_TEST/bin/Debug/net8.0/$UNIT_TEST.dll --target "dotnet" --targetargs "test --no-build" -f=opencover  -o="coverage.xml" 
    - dotnet sonarscanner end -d:sonar.login="$SONAR_TOKEN"
    # - dotnet sonarscanner begin /k:"$SONAR_PROJECT_KEY" /d:sonar.host.url="$SONAR_HOST_URL"  /d:sonar.login="$SONAR_TOKEN"  /d:sonar.cs.opencover.reportsPaths="$REPORTS_PATH/coverage.opencover.xml"  /d:sonar.analysis.mode="publish" 
    # - dotnet build ./tests/
    # - dotnet-sonarscanner end /d:sonar.login="$SONAR_TOKEN"


# dotnet sonarscanner begin -key:"passin" -d:sonar.login="admin" -d:sonar.password="admin1" -d:sonar.token="8499d72db78c461d172edde4c1b2eafc4d9348a3" -d:sonar.cs.opencover.reportsPaths="coverage.xml" -d:sonar.analysis.mode="publish" \
# && dotnet build --no-incremental  \
# && coverlet tests/UnitTests/bin/Debug/net8.0/UnitTests.dll --target "dotnet" --targetargs "test --no-build --settings coverlet.runsettings" -f=opencover  -o="coverage.xml"  \
# && dotnet sonarscanner end -d:sonar.login="8499d72db78c461d172edde4c1b2eafc4d9348a3"
